/**
 * Données des panneaux de confiance (« CERTIF ») et de périmètre de section
 * (« SECT ») du document d'audit — transcrites VERBATIM de la maquette
 * (« 4 - Etude_Patrimoniale_Partie Audit.html »), objets `CERTIF` et `SECT`.
 *
 * Ces objets alimentent le tiroir de confiance ouvert au clic sur un badge
 * `.cert` / `.synth-cert` (data-certif). La logique d'ouverture vit dans
 * use-etude-behaviors.ts ; le rendu dans EtudeAuditClient.tsx.
 *
 * Rebrand : « PRIVEOS » → « ASTRAEOS » (deux occurrences dans les libellés de
 * source juridique).
 */

/** Une ligne de décomposition de la confiance (libellé + pourcentage). */
export type CertifDet = { l: string; p: number };

/** Panneau de confiance d'un thème / bloc / section. Champs tous optionnels :
 *  les entrées CERTIF portent docs/data/loi/concl, les entrées SECT portent scope. */
export type CertifPanel = {
  lvl: string;
  h: string;
  rais: string;
  fia?: string[];
  ver?: string[];
  det?: CertifDet[];
  docs?: string[];
  data?: string[];
  loi?: string[];
  concl?: string;
  scope?: string[];
};

export const CERTIF: Record<string, CertifPanel> =
{
 theme:{fia:['Inventaire des biens et actes complets et valorisés','Encours bancaires documentés par les tableaux d’amortissement'],ver:['Valeurs de marché à fiabiliser par expertise','Quelques DPE et quotités d’assurance à confirmer'],lvl:'Confiance forte · 90 %',h:'Patrimoine immobilier — analyse globale',
  det:[{l:'Inventaire et actes (détention, capital restant dû)',p:96},{l:'Surfaces et nature des biens',p:90},{l:'Revenus locatifs (baux, quittancement)',p:84},{l:'Valeurs de marché (estimation forfaitaire)',p:78}],
  rais:'Le thème agrège des constats à fiabilité variable : l\u2019inventaire et les actes (dates, détention, capital restant dû) sont très fiables ; les valeurs de marché reposent sur une estimation forfaitaire (≈ 10 000 €/m²) introduisant une incertitude. La confiance globale est la moyenne pondérée des blocs.',
  docs:['Inventaire des actifs immobiliers','Actes d\u2019acquisition et tableaux d\u2019amortissement','Comptes locatifs et avis d\u2019imposition'],
  data:['Valeurs de marché et coûts d\u2019acquisition corrigés','Loyers, charges et rendements nets','Plus-values latentes et capital restant dû'],
  loi:['Régime des plus-values immobilières','Location meublée non professionnelle (LMNP)'],
  concl:'Inventaire solide ; valorisations à fiabiliser par expertise pour sécuriser les arbitrages.'},
 refi:{det:[{l:'Inventaire des biens (relevés)',p:98},{l:'Capital restant dû (amortissement)',p:97},{l:'Quotité bancaire retenue',p:88}],fia:['Valeurs des biens et capital restant dû issus des pièces collectées','Deux financements en cours clairement identifiés'],ver:['Quotité réellement accordée par la banque (60–70 % retenu par prudence)','Conditions de taux d’un nouveau crédit'],lvl:'Confiance forte · 95 %',h:'Potentiel de refinancement',
  rais:'Constat fondé sur des données constatées : valeurs de marché de l\u2019inventaire et capital restant dû constaté. La seule appréciation porte sur la quotité de financement retenue (prudente, 60 à 70 %).',
  docs:['Inventaire des actifs immobiliers','Tableaux d\u2019amortissement (capital restant dû)'],
  data:['Valeur du parc 1 167 000 €','Capital restant dû 240 000 €','Service de la dette ≈ 20 976 €/an'],
  loi:['Crédit hypothécaire / prêt garanti par hypothèque'],
  concl:'Capacité de levier encore disponible → ≈ 460 000 à 577 000 € mobilisables, nets du capital restant dû.'},
 crl:{det:[{l:'Contribution acquittée (avis)',p:93},{l:'Qualification de la détention',p:87},{l:'Conditions d’assujettissement',p:80}],fia:['Montants de contribution relevés sur les avis','Détention en personne physique établie'],ver:['Confirmation du non-assujettissement au cas par cas','Stabilité du régime sur la période de régularisation'],lvl:'Confiance forte · 87 %',h:'Contribution sur les revenus locatifs',
  rais:'Le règlement de la contribution est constaté sur les avis. L\u2019analyse de non-assujettissement repose sur la qualification juridique (détention par des personnes physiques), solide mais à confirmer au cas par cas.',
  docs:['Avis d\u2019imposition','Comptes locatifs'],
  data:['Contribution acquittée : 180 € et 207 €','Détention en personne physique'],
  loi:['Régime de la contribution sur les revenus locatifs'],
  concl:'Assujettissement non fondé → régularisation et remboursement (3 ans) envisageables.'},
 dpe:{det:[{l:'DPE communiqués (relevés)',p:95},{l:'Surfaces et millésimes',p:90},{l:'Impact sur valeur et location',p:80}],fia:['Classes énergétiques issues des DPE fournis','Biens locatifs concernés identifiés'],ver:['Validité des DPE (durée de dix ans)','Calendrier d’interdiction de location selon les classes'],lvl:'Confiance forte · 89 %',h:'Diagnostic de performance énergétique',
  rais:'L\u2019absence de diagnostic valide est constatée au dossier. Les conséquences (nullité, amendes, gel des loyers) découlent directement de la réglementation en vigueur.',
  docs:['Dossier locatif','Baux en cours'],
  data:['Biens sans diagnostic en cours de validité','Obligation d\u2019opposabilité pour location et vente'],
  loi:['Réglementation sur la décence énergétique et l\u2019opposabilité du diagnostic'],
  concl:'Risque réglementaire et de dépréciation → réaliser les diagnostics avant relocation ou vente.'},
 lmnpreg:{det:[{l:'Recettes meublées (relevés)',p:94},{l:'Conditions du régime',p:90},{l:'Amortissements pratiqués',p:84}],fia:['Recettes meublées sous le seuil professionnel','Bien meublé loué correctement identifié'],ver:['Tenue effective de la comptabilité LMNP','Cohérence des amortissements déclarés'],lvl:'Confiance forte · 90 %',h:'Régime de la location meublée non professionnelle',
  rais:'Régime déterminé à partir de données constatées (recettes, autres revenus du foyer). La principale incertitude porte sur la trajectoire future des recettes, susceptible de faire évoluer le statut.',
  docs:['Liasse fiscale de la location meublée','Avis d\u2019imposition du foyer'],
  data:['Recettes locatives 18 000 €','Seuils LMP (23 000 € et autres revenus)','Amortissements pratiqués'],
  loi:['CGI, art. 155, IV','CGI, art. 150 VB III','BOI-BIC-CHAMP-40-20'],
  concl:'Statut non professionnel confirmé ; vigilance sur les seuils et la fiscalité de la plus-value.'},
 lmp:{det:[{l:'Recettes meublées du foyer',p:92},{l:'Conditions de basculement',p:86},{l:'Conséquences sociales et fiscales',p:82}],fia:['Recettes meublées totalisées au niveau du foyer','Seuil de 23 000 € apprécié'],ver:['Comparaison recettes meublées / revenus du foyer','Affiliation sociale en cas de bascule en LMP'],lvl:'Confiance forte · 88 %',h:'Régime de la location meublée professionnelle (cas-test)',
  rais:'Cas-test illustratif : les paramètres (recettes, durée d\u2019activité, amortissements) sont posés pour démontrer le mécanisme. Sur un dossier réel, ces valeurs seraient issues des liasses fiscales et conditionneraient l\u2019exonération.',
  docs:['Liasses fiscales de l\u2019activité meublée','Tableau d\u2019amortissement','Avis d\u2019imposition du foyer'],
  data:['Recettes 48 000 €','Amortissements cumulés 120 000 €','Durée d\u2019activité supérieure à 5 ans'],
  loi:['CGI, art. 39 duodecies','CGI, art. 151 septies','CGI, art. 155 IV','CGI, art. 975'],
  concl:'Plus-value scindée court / long terme, exonérée sous condition de recettes et de durée (art. 151 septies).'},
 assur:{det:[{l:'Contrat communiqué',p:85},{l:'Quotités et garanties',p:78},{l:'Caractère exceptionnel du produit',p:68}],fia:['Existence du contrat d’assurance emprunteur','Prêts couverts identifiés'],ver:['Quotités exactes assurées par tête','Garanties réellement souscrites (ITT, IPT, PTIA)','Conditions du produit qualifié d’exceptionnel'],lvl:'Confiance modérée · 78 %',h:'Assurance emprunteur — produit exceptionnel',
  rais:'L\u2019analyse repose sur une jurisprudence établie et la doctrine fiscale ; la confiance est modérée car l\u2019impact chiffré dépend du régime exact de chaque structure et des clauses du contrat d\u2019assurance, à vérifier au cas par cas.',
  docs:['Contrats de prêt et d\u2019assurance emprunteur','Statuts et régime fiscal des SCI'],
  data:['Capital restant dû par structure','Têtes assurées et quotités','Régime (impôt sur le revenu / sur les sociétés)'],
  loi:['CE, 6 août 2008, n°301336','CGI, art. 38 et 38 quater','BOI-RFPI-BASE-20-80'],
  concl:'Risque fiscal réel à anticiper ; étalement possible sur 5 ans en société à l\u2019impôt sur les sociétés.'},
 dech:{det:[{l:'Encours par établissement',p:82},{l:'Clauses de déchéance du terme',p:74},{l:'Articulation des sûretés',p:68}],fia:['Répartition des encours entre établissements','Pluralité de prêteurs établie'],ver:['Clauses de déchéance propres à chaque contrat','Interdépendance éventuelle entre les crédits','Garanties croisées entre établissements'],lvl:'Confiance modérée · 75 %',h:'Multiplicité des banques — déchéance du terme',
  rais:'Le risque est de nature contractuelle : sa réalisation dépend des clauses précises de chaque prêt et de l\u2019exactitude des déclarations. L\u2019analyse signale une vigilance ; la probabilité exacte n\u2019est pas quantifiable a priori.',
  docs:['Contrats de prêt (clauses de déchéance)','Déclarations d\u2019engagements remises aux prêteurs'],
  data:['Liste des prêts et établissements','Sûretés et engagements croisés'],
  loi:['Code civil, art. 1103 et 1104'],
  concl:'Vigilance : fiabiliser les déclarations et cartographier les engagements.'},
 passifth:{fia:['Encours et tableaux d’amortissement documentés','Cautions solidaires des SCI identifiées'],ver:['Quotités d’assurance et clauses de chaque prêt','Stabilité des revenus retenus pour le ratio'],lvl:'Confiance forte · 92 %',h:'Analyse du passif — analyse globale',
  det:[{l:'Capital restant dû (amortissement)',p:97},{l:'Conditions des prêts (taux, durée)',p:93},{l:'Cautions solidaires (engagements)',p:88},{l:'Taux d’endettement (revenus)',p:86}],
  rais:'Le thème agrège des constats très fiables — capital restant dû et conditions des financements — et une analyse de l’exposition personnelle au titre des cautions solidaires. Le taux d’endettement dépend des revenus du foyer, retenus à partir des éléments déclarés.',
  docs:['Tableaux d’amortissement des prêts','Contrats de prêt et actes de cautionnement','Avis d’imposition du foyer'],
  data:['Capital restant dû par financement','Service annuel de la dette','Cautions solidaires consenties aux SCI'],
  loi:['Cautionnement solidaire de l’associé','Responsabilité aux dettes sous séparation de biens'],
  concl:'Endettement maîtrisé ; vigilance sur l’exposition personnelle au titre des cautions solidaires.'},
 budgetth:{fia:['Revenus et charges issus des avis d’imposition','Service de la dette documenté'],ver:['Régime fiscal exact de chaque SCI','Loyers des SCI retenus'],lvl:'Confiance forte · 90 %',h:'Analyse du budget — analyse globale',
  det:[{l:'Revenus du foyer',p:92},{l:'Charges et impôts',p:90},{l:'Service de la dette',p:94},{l:'Réintégration des SCI',p:80}],
  rais:'Le thème rapproche revenus et charges du foyer pour en dégager la capacité d’épargne et les ratios budgétaires. Les données proviennent des avis d’imposition ; les loyers des SCI à l’impôt sur le revenu sont réintégrés à la quote-part.',
  docs:['Avis d’imposition du foyer','Comptes de résultat des activités libérales','Tableaux d’amortissement des prêts'],
  data:['Revenus par catégorie et par personne','Charges courantes, impôts et taxes','Service annuel de la dette'],
  loi:['Transparence fiscale des sociétés à l’impôt sur le revenu','Modalités de calcul du taux d’effort'],
  concl:'Budget excédentaire ; principal levier d’optimisation d’ordre fiscal.'},
 budgep:{fia:['Capacité d’épargne de 94 742 € établie au budget','Flux d’épargne mensuels documentés'],ver:['Allocation cible et supports d’investissement','Horizon et profil de risque du foyer'],lvl:'Confiance modérée · 82 %',h:'Capacité d’épargne — mobilisation et investissement',
  det:[{l:'Capacité d’épargne (budget)',p:92},{l:'Pertinence des supports proposés',p:75}],
  rais:'Le constat repose sur l’excédent d’épargne dégagé par le budget, fiable. La recommandation d’investissement dépend du profil et des objectifs du foyer, à préciser.',
  docs:['Budget du foyer','Relevés de comptes et d’épargne'],data:['Capacité d’épargne annuelle','Taux d’épargne'],loi:[],
  concl:'Excédent d’épargne à structurer vers des supports rémunérés.'},
 budgconc:{fia:['Structure des revenus issue des avis d’imposition','Part des revenus libéraux établie'],ver:['Couverture prévoyance des praticiens','Sensibilité des revenus à un arrêt d’activité'],lvl:'Confiance forte · 88 %',h:'Concentration des revenus — dépendance à l’activité libérale',
  det:[{l:'Part des revenus libéraux',p:92},{l:'Adéquation de la prévoyance',p:78}],
  rais:'La concentration des revenus sur l’activité libérale est établie à partir des avis d’imposition. L’adéquation de la couverture prévoyance reste à vérifier sur les contrats.',
  docs:['Avis d’imposition','Comptes de résultat','Contrats de prévoyance'],data:['Revenus par catégorie','Part des revenus libéraux'],loi:[],
  concl:'Forte dépendance aux revenus libéraux ; prévoyance à sécuriser.'},
 budglev:{fia:['Taux d’effort de 19,4 % établi','Marge d’endettement disponible'],ver:['Capacité d’emprunt résiduelle précise','Conditions d’un nouveau financement'],lvl:'Confiance modérée · 84 %',h:'Marge d’endettement — effet de levier',
  det:[{l:'Taux d’effort (budget)',p:90},{l:'Capacité d’emprunt résiduelle',p:78}],
  rais:'Le taux d’effort, fiable, traduit une marge d’endettement préservée. Le dimensionnement d’un financement complémentaire dépend des conditions de marché et du projet, à instruire.',
  docs:['Budget du foyer','Tableaux d’amortissement'],data:['Taux d’effort','Service de la dette'],loi:[],
  concl:'Marge d’endettement mobilisable en effet de levier.'},
 patrav:{fia:['Encours d’assurance-vie documenté','Part dans le patrimoine établie'],ver:['Clauses bénéficiaires à jour','Allocation des supports'],lvl:'Confiance modérée · 80 %',h:'Assurance-vie — levier de transmission',
  det:[{l:'Encours et part dans le patrimoine',p:92},{l:'Pertinence de la stratégie de transmission',p:74}],
  rais:'L’encours d’assurance-vie et son poids dans le patrimoine sont établis. L’optimisation de la transmission dépend des clauses bénéficiaires et des objectifs du foyer, à préciser.',
  docs:['Relevés des contrats d’assurance-vie','Clauses bénéficiaires'],data:['Encours par contrat','Allocation fonds euros / unités de compte'],loi:['Régime fiscal de l’assurance-vie à la transmission'],
  concl:'Outil de transmission à optimiser via les clauses bénéficiaires.'},
 patrpro:{fia:['Valeur du patrimoine professionnel établie','Part dans le patrimoine'],ver:['Structure de détention optimale','Modalités de cession et de transmission'],lvl:'Confiance modérée · 78 %',h:'Patrimoine professionnel — sécurisation et liquidité',
  det:[{l:'Valeur de l’outil professionnel',p:88},{l:'Schéma de structuration',p:74}],
  rais:'La valeur du patrimoine professionnel est connue. Le schéma de structuration et de transmission le plus adapté dépend de la forme d’exercice et des projets, à instruire.',
  docs:['Bilans des activités libérales','Statuts des structures d’exercice'],data:['Valeur de l’outil professionnel','Forme de détention'],loi:['Pacte Dutreil (transmission d’entreprise)'],
  concl:'Actif à sécuriser et rendre liquide par une structuration anticipée.'},
 patrtr:{fia:['Patrimoine net établi','Régime matrimonial et composition familiale connus'],ver:['Schéma de transmission retenu','Articulation des dispositifs'],lvl:'Confiance modérée · 82 %',h:'Transmission — stratégie successorale',
  det:[{l:'Patrimoine net et composition',p:90},{l:'Pertinence des leviers successoraux',p:76}],
  rais:'Le patrimoine net, le régime matrimonial et la composition familiale sont établis. Le choix et l’articulation des dispositifs de transmission dépendent des objectifs du foyer, à définir.',
  docs:['Composition du patrimoine','Contrat de mariage','Actes de détention (SCI, indivision)'],data:['Patrimoine net','Structure de détention'],loi:['Abattements et droits de mutation à titre gratuit'],
  concl:'Transmission à anticiper via donation, démembrement et assurance-vie.'},
 patrimoineth:{fia:['Bilan patrimonial réconcilié','Répartition entre conjoints établie'],ver:['Valorisations de marché à actualiser','Schéma de transmission'],lvl:'Confiance forte · 88 %',h:'Analyse du patrimoine — analyse globale',
  det:[{l:'Composition du patrimoine (bilan)',p:92},{l:'Répartition entre conjoints',p:88},{l:'Stratégie de transmission',p:78}],
  rais:'Le thème agrège un bilan patrimonial réconcilié, très fiable, et une lecture stratégique de la diversification et de la transmission. Les valorisations de marché et le schéma de transmission restent à préciser.',
  docs:['Bilan patrimonial','Relevés d’actifs','Contrat de mariage'],data:['Composition et valorisation des actifs','Répartition entre conjoints'],loi:['Droits de mutation à titre gratuit','Régime de l’assurance-vie'],
  concl:'Patrimoine diversifié et équilibré ; principal levier d’ordre successoral.'},
 retraiteth:{fia:['Relevés de carrière documentés','Estimations des régimes de retraite'],ver:['Carrière effective jusqu’au départ','Évolution des paramètres des régimes'],lvl:'Confiance forte · 88 %',h:'Analyse de la retraite — analyse globale',
  det:[{l:'Droits acquis et trimestres validés',p:90},{l:'Pensions projetées',p:84},{l:'Taux de remplacement',p:86}],
  rais:'Le thème agrège des relevés de carrière fiables et une projection des pensions issue des points acquis. Les montants définitifs dépendront de la carrière jusqu’au départ et de l’évolution des régimes.',
  docs:['Relevés de carrière','Estimations des régimes de base et complémentaires'],data:['Trimestres et points acquis','Pensions projetées par régime'],loi:['Règles de liquidation des régimes de retraite'],
  concl:'Taux de remplacement faible ; anticipation de revenus complémentaires à prévoir.'},
 retrisq:{fia:['Pensions projetées établies','Revenus professionnels du foyer connus'],ver:['Niveau de vie cible à la retraite','Dimensionnement des revenus complémentaires'],lvl:'Confiance modérée · 82 %',h:'Taux de remplacement — baisse des ressources',
  det:[{l:'Écart entre revenus actuels et pensions',p:88},{l:'Stratégie de compensation',p:74}],
  rais:'L’écart entre les revenus actuels et les pensions projetées est établi. Le dimensionnement de la stratégie de revenus complémentaires dépend du niveau de vie souhaité et de l’horizon, à préciser.',
  docs:['Estimations des régimes','Budget du foyer'],data:['Pensions projetées','Revenus professionnels actuels'],loi:[],
  concl:'Baisse de revenus de 60 % à compenser par des revenus complémentaires.'},
 fiscaliteth:{fia:['Avis d’imposition documentés','Composition du patrimoine immobilier'],ver:['Valorisation IFI à actualiser','Situation déclarative du bien étranger'],lvl:'Confiance forte · 87 %',h:'Analyse de la fiscalité — analyse globale',
  det:[{l:'Impôts et taxes établis',p:92},{l:'Pression fiscale et TMI',p:88},{l:'Analyse IFI et conformité',p:74}],
  rais:'Le thème agrège des impôts et taxes établis à partir des avis d’imposition, très fiables, et une analyse prospective de l’IFI et de la conformité du bien étranger, à confirmer sur pièces.',
  docs:['Avis d’imposition sur le revenu','Avis de taxe foncière'],data:['Impôts et taxes par poste','Assiette IFI estimée'],loi:['Règles de l’impôt sur la fortune immobilière','Obligations déclaratives des avoirs étrangers'],
  concl:'Pression fiscale élevée ; IFI et mise en conformité du bien étranger prioritaires.'},
 fiscifi:{fia:['Composition du patrimoine immobilier','Absence de passif déductible établie'],ver:['Valorisation IFI de chaque bien','Calendrier de réintégration du bien professionnel'],lvl:'Confiance modérée · 78 %',h:'Impôt sur la fortune immobilière — seuil de déclenchement',
  det:[{l:'Assiette IFI estimée',p:80},{l:'Trajectoire à la cessation d’activité',p:72}],
  rais:'L’assiette IFI est estimée à partir de la composition du patrimoine et de l’absence de passif déductible. Les valorisations et le calendrier de réintégration du bien professionnel restent à préciser.',
  docs:['État du patrimoine immobilier','Règles IFI'],data:['Valeur des biens immobiliers','Seuil et barème IFI'],loi:['Impôt sur la fortune immobilière (assiette et barème)'],
  concl:'Seuil IFI franchi dès 2026 ; assiette à structurer.'},
 fiscetr:{fia:['Existence d’un bien détenu à l’étranger','Règles déclaratives applicables'],ver:['Situation déclarative effective','Existence de comptes étrangers'],lvl:'Confiance modérée · 76 %',h:'Bien détenu à l’étranger — mise en conformité',
  det:[{l:'Obligations déclaratives identifiées',p:85},{l:'Situation déclarative à confirmer',p:68}],
  rais:'Les obligations déclaratives des biens et comptes étrangers sont établies. La situation déclarative effective du foyer reste à confirmer pour dimensionner la régularisation.',
  docs:['Documents de propriété du bien étranger','Relevés de comptes étrangers'],data:['Valeur du bien étranger','Revenus locatifs éventuels'],loi:['Obligations déclaratives des avoirs et comptes étrangers','Échange automatique d’informations (EAI)'],
  concl:'Régularisation à engager pour écarter le risque de redressement.'},
 societesth:{fia:['Statuts et pacte d’associés documentés','Dispositions testamentaires connues'],ver:['Régime fiscal définitif de la SCI','Stratégie d’optimisation à définir'],lvl:'Confiance forte · 85 %',h:'Analyse des sociétés — analyse globale',
  det:[{l:'Constats juridiques (statuts)',p:88},{l:'Statut social du dirigeant',p:85},{l:'Leviers d’optimisation',p:72}],
  rais:'Le thème agrège des constats juridiques et sociaux établis à partir des documents constitutifs, fiables, et des leviers d’optimisation (trésorerie, fiscalité) qui appellent une instruction dédiée.',
  docs:['Statuts de la SCI','Pacte d’associés','Dispositions testamentaires','Comptes annuels'],data:['Répartition du capital','Règles de majorité et de cession'],loi:['Droit des sociétés civiles','Régime social des dirigeants'],
  concl:'Gouvernance et transmission à sécuriser ; protection sociale à compléter.'},
 globfisc:{fia:['Bénéfices cumulés de 291 244 € établis'],ver:['Forme sociétale à retenir'],lvl:'Confiance forte · 86 %',h:'Sociétés — saturation fiscale des activités libérales',
  det:[{l:'Bénéfices et prélèvements',p:90},{l:'Marge de structuration',p:74}],
  rais:'Les bénéfices et prélèvements des deux entreprises individuelles sont établis ; la marge de structuration à l’IS reste à dimensionner.',
  docs:['Comptes annuels 2024','Avis d’imposition'],data:['Bénéfices cumulés','Taux de prélèvement'],loi:['Impôt sur le revenu (BNC)','Impôt sur les sociétés'],
  concl:'Encapsulation des activités à l’IS à étudier.'},
 globjur:{fia:['Documents constitutifs documentés'],ver:['Pacte et legs à revoir'],lvl:'Confiance modérée · 80 %',h:'Sociétés — fragilité juridique et successorale de la SCI',
  det:[{l:'Statuts et testaments',p:88},{l:'Schémas correctifs',p:74}],
  rais:'Les règles statutaires et testamentaires sont établies ; les schémas correctifs (pacte, clause d’agrément, révision des legs) restent à arbitrer.',
  docs:['Statuts de la SCI','Dispositions testamentaires'],data:['Répartition du capital','Règles de majorité'],loi:['Droit des sociétés civiles'],
  concl:'Gouvernance et transmission de la SCI à sécuriser.'},
 globtres:{fia:['Soldes établis'],ver:['Supports de placement à définir'],lvl:'Confiance forte · 85 %',h:'Sociétés — trésoreries professionnelles dormantes',
  det:[{l:'Soldes et niveaux de trésorerie',p:88},{l:'Stratégie de placement',p:76}],
  rais:'Les soldes et niveaux de trésorerie sont connus ; la stratégie de placement et d’extraction reste à définir.',
  docs:['Relevés bancaires professionnels'],data:['Soldes de trésorerie','Fonds de sécurité'],loi:[],
  concl:'Trésoreries à mobiliser et placer.'},
 scijur:{fia:['Statuts documentés'],ver:['Pacte d’associés à mettre en place'],lvl:'Confiance modérée · 80 %',h:'SCI — analyse juridique',
  det:[{l:'Statuts et pacte d’associés',p:88},{l:'Conséquences successorales',p:78}],
  rais:'Les règles de gouvernance et les dispositions testamentaires sont établies ; leurs conséquences découlent de leur application combinée.',
  docs:['Statuts de la SCI','Pacte d’associés','Dispositions testamentaires'],data:['Répartition du capital','Règles de majorité'],loi:['Droit des sociétés civiles'],
  concl:'Gouvernance et transmission à sécuriser.'},
 scisoc:{fia:['Statut de gérante établi'],ver:['Contrats personnels à vérifier'],lvl:'Confiance modérée · 80 %',h:'SCI — analyse sociale',
  det:[{l:'Statut du dirigeant',p:85},{l:'Couverture sociale',p:78}],
  rais:'Le statut de gérante non rémunérée est établi ; la couverture sociale repose sur les contrats personnels, à confirmer sur pièces.',
  docs:['Statuts','Comptes annuels','Contrats d’assurance'],data:['Statut du gérant','Charges sociales'],loi:['Régime social des dirigeants'],
  concl:'Aucune protection sociale portée par la SCI.'},
 scitres:{fia:[],ver:['Comptes de la SCI à obtenir'],lvl:'À instruire',h:'SCI — optimisation de la trésorerie',
  det:[{l:'Données de trésorerie',p:40}],
  rais:'Analyse à mener dès réception des comptes de la SCI ; aucun chiffre n’est établi à ce stade.',
  docs:['Comptes de la SCI'],data:['BFR','Solde de trésorerie'],loi:[],
  concl:'À compléter sur pièces comptables.'},
 scifisc:{fia:[],ver:['Régime fiscal à confirmer'],lvl:'À instruire',h:'SCI — optimisation fiscale',
  det:[{l:'Leviers fiscaux',p:45}],
  rais:'Présentation méthodologique ; les leviers seront chiffrés selon le régime définitif et les objectifs.',
  docs:['Régime fiscal de la SCI'],data:['Régime d’imposition'],loi:['Régime mère-fille','Pacte Dutreil'],
  concl:'Leviers à instruire.'},
 scith:{fia:['Documents constitutifs'],ver:['Régime fiscal définitif'],lvl:'Confiance forte · 85 %',h:'SCI — analyse globale',
  det:[{l:'Constats juridiques',p:88},{l:'Statut social',p:85},{l:'Leviers d’optimisation',p:72}],
  rais:'Le thème agrège des constats juridiques et sociaux fiables et des leviers d’optimisation à instruire.',
  docs:['Statuts','Pacte d’associés','Comptes'],data:['Gouvernance','Cession des parts'],loi:['Droit des sociétés civiles'],
  concl:'Gouvernance à sécuriser ; protection sociale à compléter.'},
 eimsoc:{fia:['Comptes et contrats documentés'],ver:['Garanties à confirmer sur contrats'],lvl:'Confiance forte · 88 %',h:'EI Monsieur — analyse sociale',
  det:[{l:'Statut et cotisations',p:90},{l:'Couverture et retraite',p:84}],
  rais:'Le statut social, les cotisations et la protection reposent sur les comptes et contrats transmis ; les estimations de retraite sont issues des régimes.',
  docs:['Comptes annuels 2024','Contrats Madelin','Relevés de carrière'],data:['Bénéfice et cotisations','Garanties prévoyance'],loi:['Régime social des indépendants','Régime CARCDSF'],
  concl:'Couverture loi Madelin ; dépendance au régime obligatoire pour la retraite.'},
 eimrem:{fia:['Bénéfice 176 289 € établi'],ver:['Schéma d’optimisation à définir'],lvl:'Confiance modérée · 82 %',h:'EI Monsieur — optimisation rémunération et fiscalité',
  det:[{l:'Pression fiscale et sociale',p:88},{l:'Marge de pilotage',p:72}],
  rais:'La pression fiscale et sociale est établie à partir des comptes ; les marges de pilotage dépendent d’une éventuelle structuration à l’IS.',
  docs:['Comptes annuels','Avis d’imposition'],data:['Bénéfice imposable','Taux de prélèvement'],loi:['Impôt sur le revenu (BNC)','Impôt sur les sociétés'],
  concl:'Absence de pilotage en EI ; structuration à l’IS à étudier.'},
 eimtres:{fia:['Charges et soldes établis'],ver:['Support de placement à définir'],lvl:'Confiance forte · 87 %',h:'EI Monsieur — optimisation de la trésorerie',
  det:[{l:'BFR et fonds de sécurité',p:88},{l:'Performance de la trésorerie',p:82}],
  rais:'Le BFR et le fonds de sécurité sont calculés à partir des charges d’exploitation ; le solde de trésorerie est connu.',
  docs:['Comptes annuels','Relevés bancaires professionnels'],data:['Charges d’exploitation','Solde de trésorerie'],loi:[],
  concl:'Trésorerie excédentaire statique à mobiliser.'},
 eimfiscS:{fia:['Régime BNC établi'],ver:['Schéma à l’IS à instruire'],lvl:'Confiance modérée · 80 %',h:'EI Monsieur — optimisation fiscale',
  det:[{l:'Structuration BNC',p:86},{l:'Schéma à l’IS',p:72}],
  rais:'Le régime BNC et la transparence fiscale sont établis ; le schéma de structuration à l’IS reste à dimensionner.',
  docs:['Comptes annuels','Avis d’imposition'],data:['Bénéfice imposable','Taux d’imposition'],loi:['Impôt sur les sociétés','Apport d’activité'],
  concl:'Structuration à l’IS à étudier.'},
 eimfisc:{fia:['Bénéfice imposable établi'],ver:['Forme sociétale à retenir'],lvl:'Confiance modérée · 80 %',h:'EI Monsieur — structuration fiscale (BNC)',
  det:[{l:'Régime BNC',p:86},{l:'Pression fiscale',p:82}],
  rais:'Le régime BNC à l’impôt sur le revenu est établi ; l’opportunité d’un passage à l’IS dépend des objectifs et du niveau de prélèvement.',
  docs:['Avis d’imposition','Comptes annuels'],data:['Bénéfice net','TMI'],loi:['Impôt sur le revenu','Impôt sur les sociétés'],
  concl:'Pression fiscale maximale ; passage à l’IS à étudier.'},
 eimth:{fia:['Comptes établis'],ver:['Schéma de structuration'],lvl:'Confiance forte · 86 %',h:'EI Monsieur — analyse globale',
  det:[{l:'Constats sociaux et fiscaux',p:88},{l:'Leviers de structuration',p:74}],
  rais:'Le thème agrège des constats sociaux et fiscaux fiables et des leviers de structuration à dimensionner.',
  docs:['Comptes annuels','Avis d’imposition','Contrats'],data:['Bénéfice et prélèvements','Trésorerie'],loi:['Impôt sur le revenu','Impôt sur les sociétés'],
  concl:'Saturation fiscale ; transformation de l’outil professionnel à engager.'},
 eifsoc:{fia:['Comptes et contrats documentés'],ver:['Garanties à confirmer sur contrats'],lvl:'Confiance forte · 88 %',h:'EI Madame — analyse sociale',
  det:[{l:'Statut et cotisations',p:90},{l:'Couverture et retraite',p:84}],
  rais:'Le statut social, les cotisations et la protection reposent sur les comptes et contrats transmis ; les estimations de retraite sont issues des régimes.',
  docs:['Comptes annuels 2024','Contrats Madelin','Relevés de carrière'],data:['Bénéfice et cotisations','Garanties prévoyance'],loi:['Régime social des indépendants','Régime CARCDSF'],
  concl:'Couverture loi Madelin ; dépendance au régime obligatoire pour la retraite.'},
 eifrem:{fia:['Bénéfice 114 955 € établi'],ver:['Schéma d’optimisation à définir'],lvl:'Confiance modérée · 82 %',h:'EI Madame — optimisation rémunération et fiscalité',
  det:[{l:'Pression fiscale et sociale',p:88},{l:'Marge de pilotage',p:72}],
  rais:'La pression fiscale et sociale est établie à partir des comptes ; les marges de pilotage dépendent d’une éventuelle structuration à l’IS.',
  docs:['Comptes annuels','Avis d’imposition'],data:['Bénéfice imposable','Taux de prélèvement'],loi:['Impôt sur le revenu (BNC)','Impôt sur les sociétés'],
  concl:'Absence de pilotage en EI ; structuration à l’IS à étudier.'},
 eiftres:{fia:['Charges et soldes établis'],ver:['Support de placement à définir'],lvl:'Confiance forte · 87 %',h:'EI Madame — optimisation de la trésorerie',
  det:[{l:'BFR et fonds de sécurité',p:88},{l:'Performance de la trésorerie',p:82}],
  rais:'Le BFR et le fonds de sécurité sont calculés à partir des charges d’exploitation ; le solde de trésorerie est connu.',
  docs:['Comptes annuels','Relevés bancaires professionnels'],data:['Charges d’exploitation','Solde de trésorerie'],loi:[],
  concl:'Trésorerie excédentaire statique à mobiliser.'},
 eiffiscS:{fia:['Régime BNC établi'],ver:['Schéma à l’IS à instruire'],lvl:'Confiance modérée · 80 %',h:'EI Madame — optimisation fiscale',
  det:[{l:'Structuration BNC',p:86},{l:'Schéma à l’IS',p:72}],
  rais:'Le régime BNC et la transparence fiscale sont établis ; le schéma de structuration à l’IS reste à dimensionner.',
  docs:['Comptes annuels','Avis d’imposition'],data:['Bénéfice imposable','Taux d’imposition'],loi:['Impôt sur les sociétés','Apport d’activité'],
  concl:'Structuration à l’IS à étudier.'},
 eiffisc:{fia:['Bénéfice imposable établi'],ver:['Forme sociétale à retenir'],lvl:'Confiance modérée · 80 %',h:'EI Madame — structuration fiscale (BNC)',
  det:[{l:'Régime BNC',p:86},{l:'Pression fiscale',p:82}],
  rais:'Le régime BNC à l’impôt sur le revenu est établi ; l’opportunité d’un passage à l’IS dépend des objectifs et du niveau de prélèvement.',
  docs:['Avis d’imposition','Comptes annuels'],data:['Bénéfice net','TMI'],loi:['Impôt sur le revenu','Impôt sur les sociétés'],
  concl:'Pression fiscale maximale ; passage à l’IS à étudier.'},
 eifth:{fia:['Comptes établis'],ver:['Schéma de structuration'],lvl:'Confiance forte · 86 %',h:'EI Madame — analyse globale',
  det:[{l:'Constats sociaux et fiscaux',p:88},{l:'Leviers de structuration',p:74}],
  rais:'Le thème agrège des constats sociaux et fiscaux fiables et des leviers de structuration à dimensionner.',
  docs:['Comptes annuels','Avis d’imposition','Contrats'],data:['Bénéfice et prélèvements','Trésorerie'],loi:['Impôt sur le revenu','Impôt sur les sociétés'],
  concl:'Saturation fiscale ; transformation de l’outil professionnel à engager.'},
 socgouv:{fia:['Répartition du capital (50/50)','Règles de majorité et dispositions testamentaires'],ver:['Pacte d’associés à mettre en place','Révision des legs à arbitrer'],lvl:'Confiance modérée · 80 %',h:'Gouvernance et transmission — risque de paralysie',
  det:[{l:'Règles de gouvernance (statuts)',p:88},{l:'Conséquences successorales',p:78}],
  rais:'Les règles de gouvernance et les dispositions testamentaires sont établies. Leurs conséquences au premier décès découlent de l’application combinée des statuts et des legs ; les schémas correctifs restent à arbitrer.',
  docs:['Statuts de la SCI','Dispositions testamentaires'],data:['Répartition du capital','Règles de majorité (AGO/AGE)'],loi:['Droit des sociétés civiles','Démembrement et droit de vote'],
  concl:'Risque de blocage au premier décès ; pacte et legs à revoir.'},
 soccess:{fia:['Clauses statutaires de cession des parts'],ver:['Volonté de sécuriser les cessions','Modalités notariées à prévoir'],lvl:'Confiance modérée · 80 %',h:'Cession des parts — risque de fraude et recouvrement',
  det:[{l:'Clauses de cession (statuts)',p:86},{l:'Portée du risque de recouvrement',p:76}],
  rais:'Les clauses statutaires autorisant la cession sous seing privé sont établies. La portée du risque (fraude, recouvrement) découle de l’absence de titre exécutoire ; la correction passe par une clause de recours à l’acte authentique.',
  docs:['Statuts de la SCI'],data:['Clauses de cession des parts'],loi:['Acte authentique et force exécutoire','Cession de parts de société civile'],
  concl:'Cessions à sécuriser par l’acte notarié.'},
 caut:{det:[{l:'Existence des cautions (prêts SCI)',p:90},{l:'Étendue de l’engagement',p:78},{l:'Articulation avec la séparation de biens',p:74}],fia:['Cautionnement solidaire sur les prêts SCI établi','Encours cautionné de 460 000 € identifié'],ver:['Étendue exacte de l’engagement (actes)','Articulation avec le régime matrimonial'],lvl:'Confiance modérée · 80 %',h:'Caution solidaire — exposition personnelle',
  rais:'L’existence d’un cautionnement solidaire sur les prêts SCI est établie ; l’étendue exacte de l’engagement et son articulation avec le régime de séparation de biens doivent être confirmées sur les actes de prêt et de cautionnement.',
  docs:['Contrats de prêt des SCI','Actes de cautionnement solidaire','Contrat de mariage (séparation de biens)'],
  data:['Encours cautionné : 460 000 €','Têtes engagées et étendue de la caution'],
  loi:['Cautionnement solidaire — base ASTRAEOS (à valider)'],
  concl:'Exposition personnelle réelle ; renégociation et délégation d’assurance à étudier (préconisations).'},
 veille:{det:[{l:'Taux des contrats (relevés)',p:97},{l:'Conditions de marché',p:88},{l:'Point mort d’un rachat',p:84}],fia:['Taux nominaux des financements relevés','Lignes au-dessus du marché identifiées'],ver:['Conditions exactes d’un nouveau crédit','Indemnités de remboursement anticipé à confirmer'],lvl:'Confiance forte · 90 %',h:'Charge d’emprunt — veille des taux',
  rais:'Le constat croise les taux des contrats et les conditions de marché à durée équivalente. L’opportunité de rachat dépend du point mort, fonction des indemnités de remboursement anticipé et des frais.',
  docs:['Tableaux d’amortissement des prêts','Conditions de marché à date'],
  data:['Taux nominaux 1,95 % à 4,90 %','Indemnités de remboursement anticipé'],
  loi:['Remboursement anticipé — conditions contractuelles'],
  concl:'Surveiller les taux ; rachat à étudier sur les lignes les plus chères au point mort favorable.'},
 assemp:{det:[{l:'Quotités assurées (contrat)',p:88},{l:'Coût de l’assurance',p:84},{l:'Règles de délégation (crédit pro)',p:70}],fia:['Quotités et coûts relevés sur le contrat','Prêts SCI concernés identifiés'],ver:['Garanties exactes souscrites (ITT, IPT, PTIA)','Étendue du droit à délégation en crédit professionnel'],lvl:'Confiance modérée · 79 %',h:'Assurance emprunteur — quotités et délégation',
  rais:'Les quotités et le coût sont constatés sur le contrat ; la marge d’optimisation dépend du droit à délégation, plus restreint en crédit professionnel, et des garanties équivalentes proposées.',
  docs:['Contrat d’assurance emprunteur','Tableaux d’amortissement des prêts SCI'],
  data:['Quotité 30 % par tête (60 % global)','Coût ≈ 80 € / mois'],
  loi:['Droit à la délégation d’assurance — base ASTRAEOS (à valider)'],
  concl:'Relever les quotités et mettre en concurrence par délégation ; protection du conjoint survivant à renforcer.'}
};

export const SECT: Record<string, CertifPanel> =
{
 sci:{lvl:'Confiance forte · 85 %',h:'La SCI — gouvernance, social et fiscalité',
  scope:['SCI patrimoniale à l’IS, détenue à parts égales (50/50)','Gouvernance, transmission et cession des parts','Protection sociale et leviers d’optimisation'],
  rais:'L’analyse repose sur les statuts, le pacte d’associés et les dispositions testamentaires transmis ; les leviers d’optimisation appellent une instruction complémentaire.',
  det:[{l:'Statuts et pacte d’associés',p:88},{l:'Statut social et fiscalité',p:80}],
  fia:['Statuts de la SCI','Dispositions testamentaires'],
  ver:['Régime fiscal définitif','Stratégie d’optimisation']},
 eim:{lvl:'Confiance forte · 86 %',h:'Entreprise individuelle de Monsieur — social, trésorerie, fiscalité',
  scope:['EI au régime BNC, bénéfice 2024 de 176 289 €','Statut social, protection et régime de retraite','Trésorerie d’exploitation et structuration fiscale'],
  rais:'Les constats reposent sur les comptes et avis transmis. La situation sociale et la pression fiscale en découlent directement ; les pistes de structuration appellent une étude dédiée.',
  det:[{l:'Comptes et avis d’imposition',p:90},{l:'Pression fiscale et sociale',p:86}],
  fia:['Comptes annuels 2024','Avis d’imposition','Contrats d’assurance'],
  ver:['Rémunération nette et prélèvements','Schéma de structuration à l’IS']},
 eif:{lvl:'Confiance forte · 86 %',h:'Entreprise individuelle de Madame — social, trésorerie, fiscalité',
  scope:['EI au régime BNC, bénéfice 2024 de 114 955 €','Statut social, protection et régime de retraite','Trésorerie d’exploitation et structuration fiscale'],
  rais:'Les constats reposent sur les comptes et avis transmis. La situation sociale et la pression fiscale en découlent directement ; les pistes de structuration appellent une étude dédiée.',
  det:[{l:'Comptes et avis d’imposition',p:90},{l:'Pression fiscale et sociale',p:86}],
  fia:['Comptes annuels 2024','Avis d’imposition','Contrats d’assurance'],
  ver:['Rémunération nette et prélèvements','Schéma de structuration à l’IS']},
 societesth:{lvl:'Confiance forte · 86 %',h:'Synthèse de l’ensemble des sociétés',
  scope:['Trois structures : une SCI et deux entreprises individuelles','Enjeux juridiques, sociaux, de trésorerie et de fiscalité','Transformation des outils professionnels'],
  rais:'La consolidation agrège les constats des trois structures. Les leviers de transformation (structuration à l’IS, sécurisation juridique, mobilisation des trésoreries) appellent une feuille de route dédiée.',
  det:[{l:'Constats par structure',p:86},{l:'Stratégie de transformation',p:74}],
  fia:['Statuts et comptes des structures','Avis d’imposition'],
  ver:['Bénéfices et prélèvements cumulés','Schéma de restructuration']},
 societes:{lvl:'Confiance forte · 85 %',h:'Analyse des sociétés — juridique, social, trésorerie et fiscalité',
  scope:['SCI détenue à parts égales (50/50) par les conjoints','Gouvernance, transmission et modalités de cession des parts','Statut social du dirigeant et protection sociale','Leviers d’optimisation de la trésorerie et de la fiscalité'],
  rais:'L’analyse repose sur les statuts, le pacte d’associés et les dispositions testamentaires transmis. Les constats juridiques et sociaux en découlent directement ; les leviers d’optimisation appellent une instruction complémentaire.',
  det:[{l:'Statuts et pacte d’associés',p:88},{l:'Statut social du dirigeant',p:85}],
  fia:['Statuts de la SCI et pacte d’associés','Dispositions testamentaires','Comptes annuels de la société'],
  ver:['Régime fiscal définitif de la SCI','Stratégie d’optimisation à définir']},
 fiscalite:{lvl:'Confiance forte · 87 %',h:'Analyse de la fiscalité — composition, pression fiscale et IFI',
  scope:['Impôts et taxes de 95 939 €, dont 91 307 € d’impôt sur le revenu','Taux de pression fiscale de 28,5 % et TMI de 41 %','Assiette IFI approchant le seuil de 1 300 000 €','Mise en conformité d’un bien détenu à l’étranger'],
  rais:'Les impôts et taxes proviennent des avis d’imposition et de taxe foncière. Les indicateurs (pression fiscale, TMI) en découlent. L’analyse IFI et la situation du bien étranger reposent sur les éléments transmis et appellent une confirmation documentaire.',
  det:[{l:'Impôts et taxes (avis d’imposition)',p:92},{l:'Analyse IFI et bien étranger',p:74}],
  fia:['Avis d’imposition et de taxe foncière','Composition du patrimoine immobilier'],
  ver:['Valorisation IFI à actualiser','Situation déclarative du bien étranger']},
 retraite:{lvl:'Confiance forte · 88 %',h:'Analyse de la retraite — droits acquis et projection des pensions',
  scope:['Droits acquis et trimestres validés des deux conjoints','Pensions projetées : 62 212 € (Monsieur) et 45 479 € (Madame) bruts par an','Cumul de 107 691 € bruts par an et taux de remplacement','Baisse de revenus de l’ordre de 60 % à la retraite'],
  rais:'L’analyse s’appuie sur les relevés de carrière et les estimations fournies par les régimes de base et complémentaires. Les pensions projetées résultent des points acquis et des valeurs de service communiquées ; les montants définitifs dépendront de la carrière effective jusqu’au départ.',
  det:[{l:'Relevés de carrière et droits acquis',p:90},{l:'Projection des pensions',p:84}],
  fia:['Relevés de carrière des deux conjoints','Estimations des régimes (base et complémentaire)'],
  ver:['Carrière effective jusqu’au départ','Évolution des valeurs de service du point']},
 intro:{lvl:'Confiance forte · 99 %',h:'Introduction — objet et méthodologie',
  scope:['Objet et périmètre de la mission','Approche en quatre piliers','Sources mobilisées (DCI, pièces transmises)','Méthodologie en deux phases'],
  rais:'Section rédactionnelle standard : objet, périmètre, sources et méthodologie. Aucune donnée chiffrée n’y est produite ; le contenu ne requiert pas de vérification.',
  det:[{l:'Conformité du périmètre annoncé',p:99},{l:'Cohérence de la méthodologie',p:98}],
  fia:['Objet, périmètre et méthodologie conformes au cadre ASTRAEOS','Sources clairement identifiées'],
  ver:['Aucune donnée chiffrée à vérifier dans cette section']},
 situation:{lvl:'Confiance forte · 92 %',h:'Situation du foyer — données collectées',
  scope:['Composition du foyer et enfants','Régime matrimonial et événements familiaux','Situation professionnelle et fiscale','Coordonnées'],
  rais:'Les données proviennent du Document de Collecte d’Informations et des pièces transmises. La structure familiale et le régime matrimonial sont établis ; quelques éléments déclaratifs restent à confirmer par pièces.',
  det:[{l:'Composition du foyer (état civil)',p:96},{l:'Régime matrimonial',p:94},{l:'Situation professionnelle et fiscale',p:86}],
  fia:['Composition du foyer et régime matrimonial établis','Situation professionnelle des conjoints renseignée'],
  ver:['Justificatifs de certains éléments déclaratifs','Cohérence avec le dernier avis d’imposition']},
 objectifs:{lvl:'Confiance forte · 90 %',h:'Rappel des objectifs — expression du client',
  scope:['Objectifs patrimoniaux exprimés','Horizons et priorités','Contraintes éventuelles'],
  rais:'Les objectifs sont repris de l’expression directe du client (DCI et entretien). Leur formulation est fidèle ; leur hiérarchisation pourra être affinée en restitution.',
  det:[{l:'Fidélité à l’expression du client',p:94},{l:'Complétude des objectifs',p:88},{l:'Hiérarchisation des priorités',p:84}],
  fia:['Objectifs repris fidèlement de l’expression du client','Horizons d’investissement renseignés'],
  ver:['Hiérarchisation des priorités à confirmer en restitution','Objectifs implicites éventuels à expliciter']},
 patrimoine:{lvl:'Confiance forte · 88 %',h:'Analyse du patrimoine — vue d’ensemble',
  scope:['Bilan patrimonial (brut, net, passif)','Diversification par classe d’actifs','Liquidité du patrimoine','Répartition entre conjoints'],
  rais:'La vue d’ensemble agrège des données à fiabilité variable : inventaire et encours sont solides, les valeurs de marché reposent sur des estimations. La répartition entre conjoints découle du régime de séparation de biens.',
  det:[{l:'Inventaire et encours',p:95},{l:'Ventilation par classe et liquidité',p:88},{l:'Valeurs de marché (estimations)',p:78}],
  fia:['Bilan brut, net et passif cohérents','Ventilation par classe d’actifs et par conjoint établie'],
  ver:['Valeurs de marché à fiabiliser par expertise','Affectation de quelques actifs entre conjoints']},
 classes:{lvl:'Confiance forte · 89 %',h:'Analyse des classes d’actifs — détail par thème',
  scope:['Patrimoine immobilier — confiance forte · 90 %','Patrimoine financier — confiance forte · 89 %'],
  rais:'Cette section détaille chaque classe d’actifs. Le patrimoine immobilier (inventaire, revenus, fiscalité, refinancement) et le patrimoine financier (enveloppes, liquidité, performance) sont analysés séparément, chacun avec son propre niveau de confiance.',
  det:[{l:'Patrimoine immobilier',p:90},{l:'Patrimoine financier',p:89}],
  fia:['Inventaires immobilier et financier complets','Revenus, liquidité et fiscalité documentés'],
  ver:['Valeurs de marché et quelques DPE','Frais et rendements précis de certains contrats']},
 passif:{lvl:'Confiance forte · 92 %',h:'Analyse du passif — endettement et structure',
  scope:['Tableau des dettes réconcilié au passif de 715 000 €','Ventilation par nature et par détenteur','Taux d’endettement personnel et consolidé','Cautions solidaires consenties aux sociétés'],
  rais:'Le passif s’appuie sur des données constatées : capital restant dû et conditions des prêts issus des tableaux d’amortissement. La part d’appréciation porte sur la réintégration des cautions solidaires dans l’exposition personnelle et sur le taux d’endettement, fonction des revenus du foyer.',
  det:[{l:'Capital restant dû et conditions des prêts',p:96},{l:'Service annuel de la dette',p:94},{l:'Réintégration des cautions (analyse)',p:88},{l:'Revenus du foyer (taux d’endettement)',p:86}],
  fia:['Encours et tableaux d’amortissement documentés','Cautions solidaires des SCI identifiées'],
  ver:['Quotités d’assurance et clauses propres à chaque prêt','Stabilité des revenus retenus pour le ratio']},
 budget:{lvl:'Confiance forte · 90 %',h:'Analyse du budget — revenus, charges et capacité d’épargne',
  scope:['Revenus annuels de 336 630 € ventilés par personne','Charges de 176 668 € et service de la dette de 65 220 €','Taux d’effort, taux d’endettement et reste à vivre','Capacité d’épargne de 94 742 € par an'],
  rais:'Le budget agrège les revenus et charges déclarés du foyer. Les revenus professionnels et fonciers proviennent des avis d’imposition ; les loyers des SCI à l’impôt sur le revenu sont réintégrés à la quote-part. Les ratios en découlent par application directe des formules retenues.',
  det:[{l:'Revenus du foyer (avis d’imposition)',p:92},{l:'Charges courantes et impôts',p:90},{l:'Service de la dette',p:94},{l:'Loyers des SCI (réintégration)',p:80}],
  fia:['Revenus et charges issus des avis d’imposition','Service de la dette documenté'],
  ver:['Régime fiscal exact de chaque SCI (IR ou IS)','Montant des loyers des SCI']}
};

/**
 * Recherche fusionnée d'un panneau par clé (CERTIF prioritaire, repli SECT,
 * puis repli final sur CERTIF.theme — exactement comme la maquette
 * `CERTIF[k]||CERTIF.theme`). sci / eim / eif n'existent que dans SECT.
 */
export function getCertifPanel(key: string): CertifPanel {
  return CERTIF[key] ?? SECT[key] ?? CERTIF.theme;
}
