import type { CatalogEntry } from "./types";

const CATEGORY = "Identité et situation familiale";

export const ENTRIES: CatalogEntry[] = [
  {
    id: "ident-piece-identite-client",
    category: CATEGORY,
    label: "Pièce d’identité du client",
    type: "Document",
    always: true,
  },
  {
    id: "ident-piece-identite-conjoint",
    category: CATEGORY,
    label: "Pièce d’identité du conjoint, partenaire ou concubin",
    type: "Document",
    anyOf: ["a_conjoint", "marie", "pacse", "concubin"],
  },
  {
    id: "ident-piece-identite-enfant",
    category: CATEGORY,
    label: "Pièce d’identité de l’enfant",
    type: "Document",
    anyOf: ["a_enfants"],
  },
  {
    id: "ident-livret-famille",
    category: CATEGORY,
    label: "Livret de famille",
    type: "Document",
    always: true,
  },
  {
    id: "ident-info-handicap-foyer",
    category: CATEGORY,
    label: "Une personne du foyer est-elle en situation de handicap ?",
    type: "Information",
    always: true,
  },
  {
    id: "ident-justificatif-handicap",
    category: CATEGORY,
    label: "Justificatif de handicap du client, du conjoint ou d’un enfant",
    type: "Document",
    allOf: ["handicap_foyer"],
  },
  {
    id: "ident-justificatif-domicile",
    category: CATEGORY,
    label: "Justificatif de domicile récent",
    type: "Document",
    always: true,
  },
  {
    id: "ident-info-coordonnees-client",
    category: CATEGORY,
    label: "Adresse, téléphone et e-mail du client",
    type: "Information",
    always: true,
  },
  {
    id: "ident-info-coordonnees-conjoint",
    category: CATEGORY,
    label: "Adresse, téléphone et e-mail du conjoint, partenaire ou concubin",
    type: "Information",
    anyOf: ["a_conjoint", "marie", "pacse", "concubin"],
  },
  {
    id: "ident-info-situation-familiale",
    category: CATEGORY,
    label: "Situation familiale actuelle du client ou du couple",
    type: "Information",
    always: true,
  },
  {
    id: "ident-contrat-mariage",
    category: CATEGORY,
    label: "Contrat de mariage",
    type: "Document",
    allOf: ["marie"],
  },
  {
    id: "ident-avenant-contrat-mariage",
    category: CATEGORY,
    label: "Avenant ou modification du contrat de mariage",
    type: "Document",
    allOf: ["marie"],
  },
  {
    id: "ident-convention-pacs",
    category: CATEGORY,
    label: "Convention de PACS",
    type: "Document",
    allOf: ["pacse"],
  },
  {
    id: "ident-divorce-client",
    category: CATEGORY,
    label: "Jugement ou convention de divorce du client",
    type: "Document",
    allOf: ["divorce"],
  },
  {
    id: "ident-divorce-conjoint",
    category: CATEGORY,
    label: "Jugement ou convention de divorce du conjoint",
    type: "Document",
    allOf: ["conjoint_divorce"],
  },
  {
    id: "ident-info-enfant-origine",
    category: CATEGORY,
    label: "L’enfant est-il issu du client, du conjoint, du couple ou d’une autre union ?",
    type: "Information",
    anyOf: ["a_enfants"],
  },
  {
    id: "ident-info-enfant-adopte",
    category: CATEGORY,
    label: "L’enfant est-il adopté ?",
    type: "Information",
    anyOf: ["a_enfants"],
  },
  {
    id: "ident-jugement-adoption",
    category: CATEGORY,
    label: "Jugement d’adoption ou acte établissant l’adoption de l’enfant",
    type: "Document",
    allOf: ["enfant_adopte"],
  },
  {
    id: "ident-info-enfant-decede",
    category: CATEGORY,
    label: "L’enfant est-il décédé ?",
    type: "Information",
    anyOf: ["a_enfants"],
  },
  {
    id: "ident-mesure-protection",
    category: CATEGORY,
    label: "Documents relatifs à une mesure de protection",
    type: "Document",
    allOf: ["mesure_protection"],
  },
];
