import type { CatalogEntry } from "./types";

/**
 * Catalogue de collecte conditionnelle — catégorie « Immobilier ».
 *
 * Source : section "## Immobilier" de docs/referentiel-documentaire-priveos.md.
 * Chaque pièce porte une condition déterministe exprimée en FactKey :
 *   - pièce socle (titre de propriété, taxe foncière, assurance habitation…) => always
 *   - pièce conditionnelle => anyOf/allOf des faits qui la déclenchent.
 *
 * Hiérarchie parent/enfant exprimée par cumul de clauses : un détail de bail
 * locatif porte anyOf:["immobilier_locatif"] + allOf:["locatif_loue"] pour
 * n'apparaître que sur un locatif effectivement loué.
 */
export const ENTRIES: CatalogEntry[] = [
  // --- Logement d'usage : régime d'occupation -------------------------------
  {
    id: "immo-usage-regime-occupation",
    category: "Immobilier",
    sub: "Logement d'usage",
    label:
      "Le foyer est-il propriétaire, locataire ou occupant à titre gratuit de son logement d'usage ?",
    type: "Information",
    always: true,
  },
  {
    id: "immo-usage-acte-acquisition",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Acte authentique d'acquisition du bien d'usage",
    type: "Document",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-titre-propriete",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Titre de propriété ou attestation immobilière",
    type: "Document",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-bail-habitation",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Bail d'habitation du logement d'usage",
    type: "Document",
    anyOf: ["locataire_residence"],
  },
  {
    id: "immo-usage-occupation-gratuite-qui",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Si occupation gratuite, qui met le bien à disposition du foyer ?",
    type: "Information",
    anyOf: ["occupant_gratuit"],
  },
  {
    id: "immo-usage-convention-occupation-gratuite",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Convention d'occupation gratuite ou mise à disposition écrite",
    type: "Document",
    anyOf: ["occupant_gratuit"],
  },
  {
    id: "immo-usage-statuts-sci",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Statuts de SCI ou société détentrice du bien d'usage",
    type: "Document",
    anyOf: ["residence_via_sci"],
  },
  {
    id: "immo-usage-convention-indivision",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Convention d'indivision",
    type: "Document",
    anyOf: ["residence_en_indivision"],
  },
  {
    id: "immo-usage-acte-donation",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Acte de donation ou donation-partage du bien d'usage",
    type: "Document",
    anyOf: ["residence_recue_donation"],
  },
  {
    id: "immo-usage-declaration-succession",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Déclaration de succession ou attestation immobilière successorale",
    type: "Document",
    anyOf: ["residence_recue_succession"],
  },
  {
    id: "immo-usage-vente-via-agence",
    category: "Immobilier",
    sub: "Logement d'usage",
    label:
      "La vente s'est-elle faite avec agence immobilière ou chasseur immobilier ?",
    type: "Information",
    anyOf: ["proprietaire_residence", "achat_via_agence"],
  },
  {
    id: "immo-usage-dpe",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "DPE du bien d'usage",
    type: "Document",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-locatif-dpe",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "DPE du bien locatif",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },

  // --- Travaux --------------------------------------------------------------
  {
    id: "immo-usage-travaux-realises",
    category: "Immobilier",
    sub: "Travaux",
    label:
      "Des travaux ont-ils été réalisés depuis l'acquisition ou l'entrée dans le patrimoine ?",
    type: "Information",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-travaux-factures",
    category: "Immobilier",
    sub: "Travaux",
    label: "Les travaux réalisés sont-ils justifiés par factures ?",
    type: "Information",
    anyOf: ["travaux_residence"],
  },
  {
    id: "immo-usage-travaux-deduits",
    category: "Immobilier",
    sub: "Travaux",
    label: "Les travaux ont-ils déjà été déduits fiscalement ?",
    type: "Information",
    anyOf: ["travaux_residence"],
  },
  {
    id: "immo-locatif-travaux-realises",
    category: "Immobilier",
    sub: "Travaux",
    label:
      "Des travaux ont-ils été réalisés sur le bien locatif depuis l'acquisition ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-travaux-factures",
    category: "Immobilier",
    sub: "Travaux",
    label: "Les travaux sont-ils justifiés par factures ?",
    type: "Information",
    anyOf: ["travaux_locatif"],
  },
  {
    id: "immo-locatif-immobilisations-amortissements",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label:
      "Détail des immobilisations ou amortissements (bilan LMP/LMNP ou société d'exploitation)",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_meuble"],
  },

  // --- Estimations (bien d'usage puis bien locatif) -------------------------
  {
    id: "immo-usage-estimation-pro",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Estimation immobilière professionnelle de moins de six mois",
    type: "Document",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-valeur-estimee-client",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Valeur estimée par le client",
    type: "Information",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-locatif-estimation-pro",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Estimation immobilière professionnelle de moins de six mois",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-valeur-estimee-client",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Valeur estimée par le client",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },

  // --- Revenus / charges du bien d'usage ------------------------------------
  {
    id: "immo-usage-genere-revenus",
    category: "Immobilier",
    sub: "Logement d'usage",
    label:
      "Le bien génère-t-il des loyers, indemnités ou remboursements de charges ?",
    type: "Information",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-bail-mise-disposition-partielle",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Bail ou convention de mise à disposition partielle",
    type: "Document",
    anyOf: ["residence_genere_revenus"],
  },
  {
    id: "immo-usage-assurance-habitation",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Contrat d'assurance habitation, MRH ou PNO",
    type: "Document",
    always: true,
  },
  {
    id: "immo-usage-cotisation-assurance-habitation",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Montant annuel de cotisation d'assurance habitation, MRH ou PNO",
    type: "Information",
    always: true,
  },
  {
    id: "immo-usage-taxe-fonciere",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Dernier avis de taxe foncière",
    type: "Document",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-taxe-habitation",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Dernier avis de taxe d'habitation ou taxe résidence secondaire",
    type: "Document",
    always: true,
  },
  {
    id: "immo-usage-cfe",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Avis de CFE lié au bien",
    type: "Document",
    anyOf: ["residence_genere_revenus"],
  },
  {
    id: "immo-usage-appels-charges-copro",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Appels de charges de copropriété",
    type: "Document",
    anyOf: ["proprietaire_residence"],
  },
  {
    id: "immo-usage-projet-vente",
    category: "Immobilier",
    sub: "Logement d'usage",
    label: "Le client envisage-t-il de vendre ce bien ?",
    type: "Information",
    anyOf: ["proprietaire_residence", "projet_vente_residence"],
  },
  {
    id: "immo-locatif-projet-vente",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Le client envisage-t-il de vendre le bien locatif ?",
    type: "Information",
    anyOf: ["immobilier_locatif", "projet_vente_locatif"],
  },

  // --- Bien locatif : titres et exploitation --------------------------------
  {
    id: "immo-locatif-acte-acquisition",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Acte authentique d'acquisition du bien locatif",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-titre-propriete",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Titre de propriété ou attestation immobilière",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-loue-ou-vacant",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Le bien est-il actuellement loué ou vacant ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-mode-exploitation",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Quel est le mode d'exploitation du bien ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-bail-en-cours",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Bail locatif en cours",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-etat-locatif",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "État locatif ou relevé de gestion locative",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-mandat-gestion",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Mandat de gestion locative",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_gere_agence"],
  },
  {
    id: "immo-locatif-avenants-bail",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Avenants au bail",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-montant-loyer",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label:
      "Montant actuel du loyer hors charges et charges facturées au locataire",
    type: "Information",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-indexation-bail",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "L'indexation prévue au bail est-elle appliquée ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-loyer-reference",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Justificatif ou source du loyer de référence applicable",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-charges-forfait-provisions",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Les charges sont-elles facturées au forfait ou en provisions ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-decompte-charges",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Décompte de charges locatives ou relevé de gestion",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-teom-recuperee",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "La TEOM est-elle récupérée auprès du locataire ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-bail-commercial",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Bail commercial ou professionnel",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_bail_commercial"],
  },
  {
    id: "immo-locatif-bail-notarie",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Bail notarié",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_bail_commercial"],
  },
  {
    id: "immo-locatif-refacturation-taxe-charges",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label:
      "La taxe foncière et les principales charges sont-elles refacturées au preneur ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_bail_commercial"],
  },
  {
    id: "immo-locatif-acte-cautionnement",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Acte de cautionnement",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_loue"],
  },
  {
    id: "immo-locatif-assurance-loyers-impayes",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Contrat d'assurance loyers impayés",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_assurance_loyers_impayes"],
  },
  {
    id: "immo-locatif-garantie-visale",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Justificatif de garantie Visale",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_garantie_visale"],
  },
  {
    id: "immo-locatif-assurance-pno",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Contrat d'assurance PNO",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-cotisation-pno",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Montant annuel de cotisation PNO",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-gere-agence",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Le bien est il géré par une agence ou une conciergerie ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-mandat-gestion-agence",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Contrat / mandat de gestion par agence / conciergerie",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_gere_agence"],
  },
  {
    id: "immo-locatif-taxe-fonciere",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Dernier avis de taxe foncière",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-cfe",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Avis de CFE lié au bien ou à l'activité locative",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_meuble"],
  },
  {
    id: "immo-locatif-appels-charges-copro",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Appels de charges de copropriété",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-frais-comptables",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Frais comptables liés au bien ?",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-frais-entretien-divers",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label:
      "Montant annuel estimé d'entretien, maintenance, petits travaux et charges diverses",
    type: "Information",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-declarations-fiscales",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Déclarations fiscales liées au bien locatif",
    type: "Document",
    anyOf: ["immobilier_locatif"],
  },
  {
    id: "immo-locatif-ifu-attestation-gestionnaire",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "IFU ou attestation fiscale de gestionnaire",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["locatif_gere_agence"],
  },
  {
    id: "immo-locatif-engagement-dispositif-fiscal",
    category: "Immobilier",
    sub: "Immobilier locatif",
    label: "Engagement locatif ou justificatifs du dispositif fiscal",
    type: "Document",
    anyOf: ["immobilier_locatif"],
    allOf: ["dispositif_fiscal_immobilier"],
  },

  // --- Crédit immobilier ----------------------------------------------------
  {
    id: "immo-credit-offre-pret-initiale",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label: "Offre de prêt immobilier initiale",
    type: "Document",
    anyOf: ["credit_immobilier"],
  },
  {
    id: "immo-credit-avenants-pret",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label: "Avenants au prêt immobilier",
    type: "Document",
    anyOf: ["credit_immobilier"],
  },
  {
    id: "immo-credit-tableau-amortissement",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label: "Dernier tableau d'amortissement actualisé",
    type: "Document",
    anyOf: ["credit_immobilier"],
  },
  {
    id: "immo-credit-conditions-generales",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label: "Conditions générales du prêt",
    type: "Document",
    anyOf: ["credit_immobilier"],
  },
  {
    id: "immo-credit-projet-remboursement-renegociation",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label:
      "Le client envisage-t-il un remboursement anticipé, une vente ou une renégociation ?",
    type: "Information",
    anyOf: ["credit_immobilier", "projet_remboursement_renegociation_pret"],
  },
  {
    id: "immo-credit-assurance-emprunteur",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label: "Notice, certificat d'adhésion ou contrat d'assurance emprunteur",
    type: "Document",
    anyOf: ["credit_immobilier"],
  },
  {
    id: "immo-credit-delegation-assurance",
    category: "Immobilier",
    sub: "Crédit immobilier",
    label: "Contrat de délégation d'assurance",
    type: "Document",
    anyOf: ["credit_immobilier"],
    allOf: ["assurance_emprunteur_deleguee"],
  },

  // --- SCPI -----------------------------------------------------------------
  {
    id: "immo-scpi-bulletin-souscription",
    category: "Immobilier",
    sub: "SCPI",
    label: "Bulletin de souscription des parts de SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
  },
  {
    id: "immo-scpi-attestation-propriete",
    category: "Immobilier",
    sub: "SCPI",
    label: "Attestation de propriété, relevé associé ou relevé annuel SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
  },
  {
    id: "immo-scpi-ifu",
    category: "Immobilier",
    sub: "SCPI",
    label: "IFU SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
  },
  {
    id: "immo-scpi-rapport-annuel",
    category: "Immobilier",
    sub: "SCPI",
    label: "Rapport annuel ou bulletin trimestriel de la SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
  },
  {
    id: "immo-scpi-fiche-quantalys",
    category: "Immobilier",
    sub: "SCPI",
    label: "Fiche Quantalys de la SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
  },
  {
    id: "immo-scpi-convention-demembrement",
    category: "Immobilier",
    sub: "SCPI",
    label: "Convention de démembrement des parts de SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
    allOf: ["scpi_demembree"],
  },
  {
    id: "immo-scpi-offre-pret",
    category: "Immobilier",
    sub: "SCPI",
    label: "Offre de prêt finançant les parts de SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
    allOf: ["scpi_financee_credit"],
  },
  {
    id: "immo-scpi-tableau-amortissement",
    category: "Immobilier",
    sub: "SCPI",
    label: "Tableau d'amortissement du prêt SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
    allOf: ["scpi_financee_credit"],
  },
  {
    id: "immo-scpi-contrat-nantissement",
    category: "Immobilier",
    sub: "SCPI",
    label: "Contrat de nantissement des parts de SCPI",
    type: "Document",
    anyOf: ["detient_scpi"],
    allOf: ["scpi_nantissement"],
  },
  {
    id: "immo-scpi-projet-conserver-ceder-renforcer",
    category: "Immobilier",
    sub: "SCPI",
    label:
      "Le client envisage-t-il de conserver, céder ou renforcer ses parts de SCPI ?",
    type: "Information",
    anyOf: ["detient_scpi"],
  },
];
